---
format:
  revealjs:
    theme: [default, main.scss]
    slide-tone: true
    chalkboard: true
revealjs-plugins:
  - codewindow
echo: false
menu: true
code-line-numbers: false
pagetitle: "Engaging reproducible presentations"
footer: "[https://github.com/numbat-tutorials/tutorial_reproducibility_with_quarto](https://github.com/numbat-tutorials/tutorial_reproducibility_with_quarto.git)"
---

::: {.center .title-text}
Engaging Reproducible Presentations
:::

## Presentations with Quarto 

With Quarto, you are not limited to just reports, you can make presentations (and websites too!)

As of now Quarto supports making presentations in the following formats,

::: {.incremental}

1. Powerpoint presentations 
2. Beamer presentations
3. RevealJS presentations
::: 

::: {.fragment}
We are going to focus primarily on RevealJS presentations
:::

## Your first Quarto presentation

:::: {.columns}

::: {.column width="60%"}
::: {.codewindow .quarto}
basic.qmd 
`````md
{{< include includes/basic.qmd >}}
`````
::: 
:::

::: {.column width=40%}
The basic markdown tips you learned previously can be used.

:::{.callout-tip}

Try changing the value for format to `pptx` or `beamer` and see how the value changes. 

:::
::: 

::::

# Images, Code and Positioning

## Adding images

:::: {.columns}

::: {.column}
::: {.codewindow .quarto}
images.qmd 
``````md
{{< include includes/images.qmd >}}
``````
:::
::: 

::: {.column}
<br>
<iframe class="slide-deck" src="includes/images.html" ></iframe>
::: 

::::


## Code and code output 

:::: {.columns}

::: {.column}
::: {.codewindow .quarto}
code-output.qmd 
``````md
{{< include includes/code-output.qmd >}}
``````
:::
::: 

::: {.column}
<br>
<iframe class="slide-deck" src="includes/code-output.html"></iframe>
::: 

:::: 

## Take a breather {.breather}

::: {.callout-note}
Try making a presentation 

- including a photo you take with your camera right now (or use an existing image in your computer)
- Add code to plot the audience engagement of this presentation up to now (use random values with sequential time steps, OR use actual values for how engaged you were)

:::


# Theming {.smaller}

## Built in themes 

Similar to the themes in reports there are several Bootstrap themes available.

``````md
format: 
  revealjs: 
    theme: simple
``````

:::{.callout-tip}
Try changing the theme of the current presentation you are working on to `simple` or any other built in theme that you fancy
:::

## Custom themes {.smaller}

You can customize the individual parts of the presentation with a custom theme.

:::: {.columns}

::: {.column}
::: {.codewindow .sass}
`````md
{{< include includes/main.scss >}}
`````
::: 
:::

::: {.column}
<br>
<iframe class="slide-deck" src="includes/theming.html"> </iframe>
::: 

::::

## Take a breather {.breather}

::: {.callout-note}
Try styling your previous presentation by 

- Change the base font color and family
- Change the heading color and family
- Change the link color and test it by adding a link to your favorite YouTube video (bonus points if its a rick roll)

:::

## Design choices {.smaller}

- Accessibility (support for visually impaired users and physically challenged users)
  - Alt texts
  - Slide tones (to indicate slide position and passing)
- Visual choices
  - Colorblind friendly color choices ([whocanuse](https://www.whocanuse.com/), [color-blindness](https://www.color-blindness.com/coblis-color-blindness-simulator/))
  - Color contrast for readability ([coolors](https://coolors.co/contrast-checker/), [colourcontrast](https://colourcontrast.cc/))
  - Theme colors for your own branding ([coolors](https://coolors.co/))
  - Readable fonts aligned with your branding ([Google](https://fonts.google.com/), [Bunny (GDPR Compliant)](https://fonts.bunny.net/))

# Additional tidbits

## Tools for the presentation time {.smaller}

::: {.incremental}
* Navigation menu (`M` key)
* Chalkboard (`C` key or `N` key, requires chalkboard: true) 
* Speaker view (`S` key) 
* Jump to slide (`G` key) 
* Overview mode (`O` key)
* Slide tone (requires `slide-tone: true`)
:::

## Animations

The simplest type of animations are incremental lists.

::::{.columns}
:::{.column}

``````md
::: {.incremental}
- Five 
- Six 
- Seven
- Eight
:::
``````
:::

:::{.column}

::: {.incremental}
- Five 
- Six 
- Seven
- Eight
:::

:::

:::: 

There are more advanced ways to animate using fragments and auto-animate options as seen [here](https://quarto.org/docs/presentations/revealjs/advanced.html#fragments).

## Hosting the presentations {.smaller}

The results of the revealjs presentation is a static HTML file.

You can use any place that can static file hosting services online to share the presentation.

Examples include, 

* Netlify
* Github pages 
* Cloudflare pages 
* Huggingface Spaces 
* Amazon S3 buckets 

# Wrapping up

## What did we learn today? {.breather}

### Group discussion time! 

Let's talk about what's one thing that we remember from this session.

<!-- Things to cover: -->
<!---->
<!-- Structure of slides -->
<!-- Hosting  -->
<!-- Using images -->
<!-- Positioning images and text -->
<!-- R code output, syntax highlighting and line highlighting -->
<!-- Speaker view, chalkboard and other presentation tools (mutliplex to follow along, a11y with ding sound to keep track) -->
<!-- Styling -->
<!-- Fragments and animations (just a slight intro) -->
<!-- Resources for more learning (slidecraft by emil, nicole's blog, mine's blog etc.) -->

<!-- | Length (minutes) | Topic | Description | -->
<!-- | --------------- | --------------- | --------------- | -->
<!-- | 5  | Overview | Structure of the entire session and what we will be covering and not covering | -->
<!-- | 5 | Presentation output types | LALALALA | -->
<!-- | 5 | Your first online presentation | LALALALA | -->
<!-- | 10 | Hosting and sharing presentations | LALALALA | -->
<!-- | 10 | Images, captions and posiitoning | LALALALA | -->
<!-- | 10 | Code outputs and highlighting | LALALALA | -->
<!-- | 5 | In presentation tools | LALALALA | -->
<!-- | 15 | Theming | LALALALA | -->
<!-- | 5 | Intro to fragments | LALALALA | -->
<!-- | 5 | Resources for future | LALALALA | -->
<!---->
